# Generated by Django 4.1.4 on 2023-03-09 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
