# Generated by Django 4.1.4 on 2023-03-09 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_remove_cart_product_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('description', models.TextField(blank=True, max_length=299, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('image', models.ImageField(upload_to='images/')),
                ('search_tag1', models.CharField(blank=True, max_length=19, null=True)),
                ('search_tag2', models.CharField(blank=True, max_length=19, null=True)),
                ('search_tag3', models.CharField(blank=True, max_length=19, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.seller')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commerce.product'),
            preserve_default=False,
        ),
    ]
