# Generated by Django 4.1.4 on 2023-03-09 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_product_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='search_tag2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='search_tag3',
        ),
    ]
