# Generated by Django 4.1.4 on 2023-03-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_remove_product_search_tag2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_tag2',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='search_tag3',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
    ]
