# Generated by Django 4.1.4 on 2023-03-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_product_search_tag2_product_search_tag3'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='nearest_landmark',
            field=models.CharField(default='modakeke', max_length=299),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='search_tag1',
            field=models.CharField(default='rado', max_length=19),
            preserve_default=False,
        ),
    ]
