# Generated by Django 4.1.4 on 2023-03-10 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0011_alter_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='query',
            new_name='queried',
        ),
    ]
