# Generated by Django 4.1.4 on 2023-03-10 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerce', '0012_rename_query_order_queried'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='received',
        ),
        migrations.AddField(
            model_name='orderquery',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderquery',
            name='issue',
            field=models.TextField(default='cdscdszdfszdszd', max_length=299),
            preserve_default=False,
        ),
    ]
